import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar.js"
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>

      <section className={styles.main}>
        <Navbar/>
        <h1 className={styles["mainheading"]}>
          Unlimited movies, TV <br />
          shows, and more.
        </h1>
        <h2 className={styles["subheading"]}>
          Watch anywhere. Cancel anytime.
        </h2>
        <p className={styles["para"]}>
          Ready to watch? Enter your email to create or restart your membership.
        </p>
        <div className={styles["getstarted-container"]}>
          <input
            type="email"
            placeholder="Email Address"
            className={styles["emailinput"]}
          />
          <button className={styles["startbutton"]}>
            Get Started
            <svg
              className={styles["chevron"]}
              viewBox="0 0 6 12"
              xmlns="http://www.w3.org/2000/svg"
            >
              <desc>chevron</desc>
              <path
                d="M.61 1.312l.78-.624L5.64 6l-4.25 5.312-.78-.624L4.36 6z"
                fill="none"
                stroke="white"
                strokeWidth="1"
                fill-rule="evenodd"
              ></path>
            </svg>
          </button>
        </div>
      </section>
    </div>
  );
}
