import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer/Footer.js";
import Navbar from "../components/Navbar/Navbar.js";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>

      <section className={styles.main}>
        <Navbar />
        <h1 className={styles["mainheading"]}>
          Unlimited movies, TV <br />
          shows, and more.
        </h1>
        <h2 className={styles["subheading"]}>
          Watch anywhere. Cancel anytime.
        </h2>
        <p className={styles["para"]}>
          Ready to watch? Enter your email to create or restart your membership.
        </p>
        <div className={styles["getstarted-container"]}>
          <input
            type="email"
            placeholder="Email Address"
            className={styles["emailinput"]}
          />
          <button className={styles["startbutton"]}>
            Get Started
            <svg
              className={styles["chevron"]}
              viewBox="0 0 6 12"
              xmlns="http://www.w3.org/2000/svg"
            >
              <desc>chevron</desc>
              <path
                d="M.61 1.312l.78-.624L5.64 6l-4.25 5.312-.78-.624L4.36 6z"
                fill="none"
                stroke="white"
                strokeWidth="1"
                fill-rule="evenodd"
              ></path>
            </svg>
          </button>
        </div>
      </section>

      {/* <hr /> */}

      <section className={styles["containers"]}>
        <div className={styles["containers-content"]}>
          <div
            className={`${styles["container-indiv"]} ${styles["container-text"]}`}
          >
            <h1 className={`${styles["containers-heading"]} ${styles.yellow}`}>
              Enjoy on your TV.
            </h1>
            <p
              className={`${styles["containers-description"]} ${styles.yellow}`}
            >
              Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV,
              Blu-ray players and more.
            </p>
          </div>
          <div
            className={`${styles["container-indiv"]} ${styles["image-container"]}`}
          >
            <img
              className={styles["container-images"]}
              src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/tv.png"
              alt="Image here"
            />
            <div className={styles["container-videos"]}>
              <video
                autoplay="true"
                playsinline="true"
                muted="true"
                loop="true"
                src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/video-tv-in-0819.m4v"
                type="video/mp4"
              ></video>
            </div>
          </div>
        </div>
      </section>

      {/* <hr /> */}

      <section>
        <div>
          <img src="" alt="" />
        </div>
        <div>
          <h1 className={`${styles["containers-heading"]} ${styles.yellow}`}>
            Download your shows to watch offline.
          </h1>
          <p className={`${styles.description} ${styles.yellow}`}>
            Save your favourites easily and always have something to watch.
          </p>
        </div>
      </section>

      {/* <hr /> */}

      <section className={styles["containers"]}>
        <div>
          <h1 className={`${styles.description} ${styles.yellow}`}>
            Watch everywhere
          </h1>
          <p className={`${styles.description} ${styles.yellow}`}>
            Stream unlimited movies and TV shows on your phone, tablet, laptop,
            and TV.
          </p>
        </div>
        <div>
          <img
            src="https://assets.nflxext.com/ffe/siteui/acquisition/ourStory/fuji/desktop/device-pile-in.png"
            alt="Image here"
          />
        </div>
      </section>

      {/* <hr /> */}

      <section className={styles["containers"]}>
        <div></div>
        <div>
          <h1 className={`${styles.description} ${styles.yellow}`}>
            Create profiles for children.
          </h1>
          <p className={`${styles.description} ${styles.yellow}`}>
            Send children on adventures with their favourite characters in a
            space made just for them—free with your membership.
          </p>
        </div>
      </section>

      {/* Footer */}
      <Footer/>
    </div>
  );
}
